### ISSUE TITLE
Installation without git

### ISSUE THREAD

**Issue by r0f1** [aerdem4/lofo-importance#13]
Hi, love you package. I'd like to install it in a cloud environment, where I do not have git available. 
I can only install packages from PyPi, or if I upload an .egg or .whl file.  Could you maybe provide details on how to install your package, given these circumstances or point me in the right direction?

Thank you, Flo

**Comment by aerdem4** [comment]
@r0f1 thanks for your interest. With the latest PR, you can now install it by:

> pip install lofo-importance
