### ISSUE TITLE
I am not able to import Dataset

### ISSUE THREAD

**Issue by ashutosh1919** [aerdem4/lofo-importance#26]
`from lofo import Dataset` doesn't work and gives error of 

> cannot import name 'Dataset' from 'lofo'

But if I write `from lofo.dataset import Dataset` then it works fine.

I think it has something to do with __init__.py

**Comment by aerdem4** [comment]
Can you give more information? Which lofo version are you using? Which Python version? Did you pip install or git clone?

It should be able to imported because this unit test passes: https://github.com/aerdem4/lofo-importance/blob/master/tests/test_lofo_importance.py#L5

**Comment by ashutosh1919** [comment]
I have tried both using pip install and git clone and both doesn't work. I am using python version 3.6 and lofo-importance version 0.2.3

**Comment by aerdem4** [comment]
I have created a clean virtualenv and tried to reproduce the issue now and couldn't reproduce.

**Comment by ashutosh1919** [comment]
@aerdem4 , Let me try creating venv in my system and will try to use it. if I face the issue, i will make PR for this issue.

**Comment by ashutosh1919** [comment]
Sorry for wrong issue @aerdem4 , It is working when I tried in venv. I think previously i was using 0.2.0. That's why it was not working.
