### ISSUE TITLE
Sample_weight?

### ISSUE THREAD

**Issue by kmedved** [aerdem4/lofo-importance#31]
Is there any way to pass a sample weight column into a Dataset object, or is there any plan to add this functionality? It should fit pretty smoothly into the sklearn framework I would expect, but maybe I'm missing something.

Thanks for the wonderful package!

**Comment by aerdem4** [comment]
@kmedved Thanks for your question. You can pass your sample weights LOFOImportance in fit_params. Example:

```
fi = LOFOImportance(dataset, scoring=scorer, model=LinearRegression(), cv=cv, 
                    fit_params={"sample_weight": df["sw"].values})
```

Let me know if it works for you.

**Comment by kmedved** [comment]
Excellent - that worked great. Thanks for the quick reply. That functionality really helps makes this a first-rate feature selection tool.

Eager to watch for future improvements.
