### ISSUE TITLE
Having a lot of features + Using LOFO?

### ISSUE THREAD

**Issue by Mymoza** [aerdem4/lofo-importance#34]
Hi, 

I have 1673 features. When I tried using LOFO importance, the result is the following: 

![lofo_importance_result](https://user-images.githubusercontent.com/9295938/93026399-b3b35380-f5d3-11ea-8b81-4f843ef5aade.png)

Are the features showing up one on top of the other because the plot isn't long enough? What would you suggest to fix this problem? 

Thank you

**Comment by aerdem4** [comment]
I think the issue is indeed with the plot. It is not able to visualize all 1673 features for given figsize. You can try larger figsize but then it may become a very large image. Can you tell me about these 1673 features? If you are able to group them, you can get better results. LOFO Dataset can take a dictionary of feature groups.

**Comment by Mymoza** [comment]
My features are from [tsfresh](https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html). The reason I have so many is that we tried different coefficients for these features, so it grows to a high number of features.

Grouping them as one would do using FLOFO? I tried doing that, but my validation set has 434 examples, and so I was not meeting the minimum requirement of 1000 examples. I wanted to change the number of bins to fix that, but it seems it is not an argument easy to give a new value..?

**Comment by aerdem4** [comment]
Grouping as in the example on README:

```
    dataset = Dataset(df=df[df[target].notnull()], target=target, features=loading_features,
                      feature_groups={"fnc": df[df[target].notnull()][fnc_features].values
                      })
```
