### ISSUE TITLE
Groupkfold or Groupshufflesplit Cross Validation

### ISSUE THREAD

**Issue by kmedved** [aerdem4/lofo-importance#37]
Thanks for the very cool package. I was wondering if it is possible to pass a group_id somehow in order to do Groupkfold or Groupshufflesplit cross validation? I don't see anywhere obvious, but wanted to check in case I'm missing anything.

Thanks.

**Comment by aerdem4** [comment]
@kmedved cv parameter supports any custom iterable (list of (train_ind, val_ind)). I suggested a workaround on #28 Please let me know if this workaround works for you.
