### ISSUE TITLE
Could you add a reference?

### ISSUE THREAD

**Issue by danielmlow** [aerdem4/lofo-importance#49]
Thanks for putting this repo together. Who developed this method? Is it the same as LOCO?
https://www.tandfonline.com/doi/full/10.1080/01621459.2017.1307116?casa_token=HAl_ErrKi18AAAAA:YyDJybfbzaLMDU1Zlzq8D4OQnZmUeEwukWJFagcsFB7_JA-W-7ifcINhc8N0FTbtbImLjezWESo

Thanks,
Daniel

**Comment by aerdem4** [comment]
Thanks for your question. If you are asking if it is based on a specific paper, the answer is no. I don't have access to the paper you shared but the idea may be similar.
