### ISSUE TITLE
Pandas 2.0.x compatibility

### ISSUE THREAD

**Issue by holzben** [aerdem4/lofo-importance#55]
Tried your package today with pandas 2.0.3 and got the following error:

`AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'`

After downgrading to Version 1.5.3 the issue was gone.

Can you please double-check and in case upgrade to pandas 2.0.x? thanks!

**Comment by aerdem4** [comment]
Thanks for creating this issue. I couldn't replicate it. Can you please provide more details on error message or share the data you try lofo on with me?

**Comment by holzben** [comment]
sure. 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/var/folders/rj/8ly58ghs4b5gh1xdc17nsdf40000gn/T/ipykernel_19018/3810989842.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/rj/8ly58ghs4b5gh1xdc17nsdf40000gn/T/ipykernel_19018/3810989842.py) in ()
     40 
     41 from sklearn.model_selection import KFold
---> 42 from lofo import LOFOImportance, Dataset, plot_importance
     43 get_ipython().run_line_magic('matplotlib', 'inline')
     44 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/__init__.py) in 
----> 1 from .lofo_importance import LOFOImportance
      2 from .flofo_importance import FLOFOImportance
      3 from .dataset import Dataset
      4 from .plotting import plot_importance

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/lofo_importance.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/lofo_importance.py) in 
      3 from tqdm.autonotebook import tqdm
      4 import warnings
----> 5 from lofo.infer_defaults import infer_model
      6 from lofo.utils import lofo_to_df, parallel_apply
      7 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/infer_defaults.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lofo/infer_defaults.py) in 
      1 import numpy as np
      2 from sklearn.preprocessing import LabelEncoder
----> 3 from lightgbm import LGBMClassifier, LGBMRegressor
      4 from lofo.utils import flatten_list
      5 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/__init__.py) in 
      6 from pathlib import Path
      7 
----> 8 from .basic import Booster, Dataset, Sequence, register_logger
      9 from .callback import early_stopping, log_evaluation, record_evaluation, reset_parameter
     10 from .engine import CVBooster, cv, train

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/basic.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/basic.py) in 
     19 import scipy.sparse
     20 
---> 21 from .compat import PANDAS_INSTALLED, concat, dt_DataTable, pd_CategoricalDtype, pd_DataFrame, pd_Series
     22 from .libpath import find_lib_path
     23 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/compat.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/lightgbm/compat.py) in 
    143     from dask.array import from_delayed as dask_array_from_delayed
    144     from dask.bag import from_delayed as dask_bag_from_delayed
--> 145     from dask.dataframe import DataFrame as dask_DataFrame
    146     from dask.dataframe import Series as dask_Series
    147     from dask.distributed import Client, Future, default_client, wait

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/__init__.py) in 
      2     import dask.dataframe._pyarrow_compat
      3     from dask.base import compute
----> 4     from dask.dataframe import backends, dispatch, rolling
      5     from dask.dataframe.core import (
      6         DataFrame,

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/backends.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/backends.py) in 
     18 from dask.array.dispatch import percentile_lookup
     19 from dask.array.percentile import _percentile
---> 20 from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
     21 from dask.dataframe.dispatch import (
     22     categorical_dtype_dispatch,

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/core.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/core.py) in 
     33 from dask.blockwise import Blockwise, BlockwiseDep, BlockwiseDepDict, blockwise
     34 from dask.context import globalmethod
---> 35 from dask.dataframe import methods
     36 from dask.dataframe._compat import PANDAS_GT_140, PANDAS_GT_150
     37 from dask.dataframe.accessor import CachedAccessor, DatetimeAccessor, StringAccessor

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/methods.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/methods.py) in 
     20     union_categoricals,
     21 )
---> 22 from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
     23 
     24 # cuDF may try to import old dispatch functions

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/utils.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/utils.py) in 
     17 from dask.base import get_scheduler, is_dask_collection
     18 from dask.core import get_deps
---> 19 from dask.dataframe import (  # noqa: F401 register pandas extension types
     20     _dtypes,
     21     methods,

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/_dtypes.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/_dtypes.py) in 
      1 import pandas as pd
      2 
----> 3 from dask.dataframe.extensions import make_array_nonempty, make_scalar
      4 
      5 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/extensions.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/extensions.py) in 
      4 See :ref:`extensionarrays` for more.
      5 """
----> 6 from dask.dataframe.accessor import (
      7     register_dataframe_accessor,
      8     register_index_accessor,

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/accessor.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/accessor.py) in 
    188 
    189 
--> 190 class StringAccessor(Accessor):
    191     """Accessor object for string properties of the Series values.
    192 

[~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/accessor.py](https://file+.vscode-resource.vscode-cdn.net/Users/tara/vscode/data-science-playbooks/~/vscode/data-science-playbooks/.venv/lib/python3.11/site-packages/dask/dataframe/accessor.py) in StringAccessor()
    274 
    275     @derived_from(
--> 276         pd.core.strings.StringMethods,
    277         inconsistencies="``expand=True`` with unknown ``n`` will raise a ``NotImplementedError``",
    278     )

AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'`

**Comment by holzben** [comment]
the package combination used looks as following: 
`[tool.poetry]
name = "data-science-playbooks"
version = "0.1.0"
description = "Some small fun examples."
authors = ["Benjamin Holzknecht <benjamin.holzknecht@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
scipy = "^1.9.0"
numpy = "^1.23.2"
featuretools = "^1.13.0"
sklearn = "^0.0"
graphviz = "^0.20.1"
jupyter-black = "^0.3.1"
xgboost = "^1.6.1"
matplotlib = "^3.5.3"
woodwork = "^0.25.0"
pyarrow = "^12.0.1"
kaggle = "^1.5.15"
requests = "^2.31.0"
seaborn = "^0.12.2"
lofo-importance = "^0.3.3"
pandas = "^2.0.3"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
`

**Comment by aerdem4** [comment]
The error seems to be not coming from LOFO. You get error while importing lightgbm:

`from lightgbm import LGBMClassifier, LGBMRegressor`

**Comment by holzben** [comment]
Ok, will check that. Thanks!
