### ISSUE TITLE
how to add weight for r2_score in lofo?

### ISSUE THREAD

**Issue by RainFung** [aerdem4/lofo-importance#63]
def r2_score(
    y_true,
    y_pred,
    *,
    sample_weight=None,
    multioutput="uniform_average",
    force_finite=True,
):

**Comment by aerdem4** [comment]
Have you tried adding it to fit_params parameter? 

https://github.com/aerdem4/lofo-importance/blob/master/lofo/lofo_importance.py#L21

`fit_params={sample_weight=your_weight_vector}`

**Comment by aerdem4** [comment]
@RainFung did it work?

**Comment by RainFung** [comment]
thanks, it worked well
